### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by DavidRSchaller** [DethAriel/ng2-recaptcha#1]
Recaptcha is working as expected in my app. however,
The following errors are thrown in to developer console:

`[default] C:\www\myapp\node_modules\ng2-recaptcha\recaptcha\recaptcha-loader.service.d.ts:3:22 
Cannot find namespace 'ReCaptchaV2'.

[default] C:\www\myapp\node_modules\ng2-recaptcha\recaptcha\recaptcha.component.d.ts:9:11 
Cannot find namespace 'ReCaptchaV2'.

[default] C:\www\myapp\node_modules\ng2-recaptcha\recaptcha\recaptcha.component.d.ts:10:10 
Cannot find namespace 'ReCaptchaV2'.

[default] C:\www\myapp\node_modules\ng2-recaptcha\recaptcha\recaptcha.component.d.ts:11:10 
Cannot find namespace 'ReCaptchaV2'.`

Thoughts on what is happening here?
I'd be happy to provide additional details if needed.

Angular2 - 2.0.0
ng2-recaptcha@1.3.1

**Comment by DethAriel** [comment]
That's because the project uses `grecaptcha` typings, and you don't have them installed. Take a look at [installation](/DethAriel/ng2-recaptcha#installation) section:

```
typings install dt~grecaptcha --save --global
```

After that typescript should be able to find the abovementioned namespace

**Comment by DavidRSchaller** [comment]
I did run that command and confirm my typings.json file:

{
  "globalDependencies": {
    "grecaptcha": "registry:dt/grecaptcha#0.0.0+20160808210619"
  }
}

I suspect it may be related to the angular-cli build process.

**Comment by DethAriel** [comment]
Can you please post the minimum required code for reproduction? E.g. a component that uses ng2-recaptcha plus the command you use to build the thing

**Comment by DavidRSchaller** [comment]
Here are the steps to reproduce the issue:

- ng new recap-test
- cd recap-test
- npm uninstall webpack --save-dev // resolve issue with bet 14 of angular-cli
- npm install webpack@2.1.0-beta.22 --save-dev // resolve issue with bet 14 of angular-cli
- npm install --save ng2-recaptcha
- typings install dt~grecaptcha --save --global

app.module.ts
----------------------------
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';

import { RecaptchaModule } from 'ng2-recaptcha';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    RecaptchaModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```


app.component.html
-----------------------------
```
<h1>
  {{title}}
	<recaptcha siteKey="-----KEY--------"></recaptcha>
</h1>
```

**Comment by DethAriel** [comment]
Confirmed the behavior. This is what you can do: add this line to your `src/typings.d.ts` file:
```
/// <reference path="../typings/index.d.ts" />
```

This will make the error go away. Another option is to move the `tsconfig.json` file up one level, and modify the `angular-cli.json` file to say `"tsconfig": "../tsconfig.json",` (although it popped up a different, non-recaptcha error for me).

Not sure what else can I do here except for dropping grecaptcha typings, which I do not consider an option. If you happen to find a better way of doing that - please, let me and others know.

**Comment by DethAriel** [comment]
Third option:
```
cd src
typings install dt~grecaptcha --save --global
```
E.g. install grecaptcha typings in `src` folder instead of project root.

**Comment by DethAriel** [comment]
@DavidRSchaller forget what I said above, with TypeScript 2 the preferred way of handling types is:
```
npm install @types/grecaptcha 
```
This definitely resolves an issue, and does not smell bad

**Comment by DavidRSchaller** [comment]
Ruslan,


Thanks for the additional follow up.

I reverted the previous fix by removing the typings.json file and typings folder.

I then installed via your mentioned method and all is working.


Thanks again!
David


________________________________
