### ISSUE TITLE
"Calling function 'RecaptchaLoaderService', function calls are not supp..." when build -prod

### ISSUE THREAD

**Issue by FrankNT** [DethAriel/ng2-recaptcha#14]
When I apply new language, it works fine in development environment

> ng serve

But when I try to build prod, I get error

> ng build -prod

> ERROR in Error encountered resolving symbol values statically. Calling function 'RecaptchaLoaderService', function calls are not supp
> replacing the function or lambda with a reference to an exported function, resolving symbol AppComponent in /Users/
> src/app/app.component.ts, resolving symbol AppComponent in /Users/ang/src/app/app.compone
> 
> ERROR in ./src/main.ts
> Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/ang/src
>  @ ./src/main.ts 4:0-74
>  @ multi ./src/main.ts

Then I have to remove RecaptchaLoaderService.

**Comment by DethAriel** [comment]
I suppose you're having trouble with this piece of code:

```ts
@NgModule({
  providers: [
    {
      provide: RecaptchaLoaderService,
      useValue: new RecaptchaLoaderService("fr"), // use French language
    },
  ],
}) export class MyModule { }
```

The compiler is telling you that it cannot parse a construction like this. What you should do instead is either this:

```ts
export const FrenchRecaptchaLoaderService = new RecaptchaLoaderService("fr");

@NgModule({
  providers: [
    {
      provide: RecaptchaLoaderService,
      useValue: FrenchRecaptchaLoaderService,
    },
  ],
}) export class MyModule { }
```

or this (the preferred approach):

```ts
import { RECAPTCHA_LANGUAGE } from 'ng2-recaptcha';

@NgModule({
  providers: [
    {
      provide: RECAPTCHA_LANGUAGE,
      useValue: 'fr', // or whatever other language you need
    },
  ],
}) export class MyModule { }
```

**Comment by FrankNT** [comment]
I tried the 2nd way. It works like a charm.
Thank you.
