### ISSUE TITLE
Unclear example

### ISSUE THREAD

**Issue by loqtor** [DethAriel/ng2-recaptcha#5]
Hi,

The module looks interesting. But when looking at the instructions is not actually clear how to set it up.

See below: 
```javascript
import { RecaptchaModule } from 'ng2-recaptcha';
import { BrowserModule }  from '@angular/platform-browser';

@NgModule({
  bootstrap: [MyApp],
  declarations: [MyApp],
  imports: [
    BrowserModule,
    RecaptchaModule.forRoot(), // Keep in mind the "forRoot"-magic nuances!
  ],
})
export class MyAppModule { }
```
There you bootstrap and declare `MyApp` which is never imported in this module. 
(By the way, `forRoot` did not do it for me. I get `Property 'forRoot' does not exist on type 'typeof ReCaptchaModule'` error. I can raise a separate issue with more information if that'd help).

And then here: 
```javascript
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { Component } from '@angular/core';

@Component({
    selector: 'my-app',
    template: `<recaptcha (resolved)="resolved($event)" siteKey="YOUR_SITE_KEY"></recaptcha>`,
}) export class MyApp {
    resolved(captchaResponse: string) {
        console.log(`Resolved captcha with response ${captchaResponse}:`);
    }
}

platformBrowserDynamic().bootstrapModule(MyAppModule);
```

You declare a new component and then export `MyApp` class. But at the end of this example you bootstrap your `AppModule` which is never imported in the example.

Can you please check on that? I've been trying to use it and I'm not sure what I'm missing. 
So if you can have the instructions corrected, that'd be awesome.

Thanks.
Cheers!

**Comment by DethAriel** [comment]
What version of Angular / TypeScript are you using?

**Comment by DethAriel** [comment]
On the `forRoot` issue - could you please open a separate bug? Please, include all relevant information (Angular version, TS version, webpack/systemjs, ...)

**Comment by loqtor** [comment]
Thanks. That's much clearer. 👍 
Cheers!
