### ISSUE TITLE
Not found issues when using systemjs loader

### ISSUE THREAD

**Issue by LucasFrecia** [DethAriel/ng2-recaptcha#9]
I can't seem to make it work on systemjs. It finds `ng2-recaptcha.noforms.js` but it fails on following requests:

```
[1] 17.01.30 04:46:34 404 GET /node_modules/ng2-recaptcha/recaptcha/recaptcha.component
[1] 17.01.30 04:46:34 404 GET /node_modules/ng2-recaptcha/recaptcha/recaptcha-loader.service
[1] 17.01.30 04:46:34 404 GET /node_modules/ng2-recaptcha/recaptcha/recaptcha-noforms.module
```

My system.config.js has followinf line to load:

` 'ng2-recaptcha' : 'node_modules/ng2-recaptcha/ng2-recaptcha.noforms.js'`

And like readme explains I call from module 

`import { RecaptchaModule } from 'ng2-recaptcha';`

Any idea what is wrong?

**Comment by afu1991** [comment]
I have a same probleme too, when i have this error : 

`Uncaught ReferenceError: require is not defined
    at eval (eval at webpackJsonp.297.module.exports (addScript.js:9), <anonymous>:11:14)
    at eval (<anonymous>)
    at webpackJsonp.297.module.exports (addScript.js:9)
    at Object.186 (angular2-recaptcha.js?d64c:1)
    at __webpack_require__ (bootstrap 2eab723…:52)
    at Object.902 (addScript.js:10)
    at __webpack_require__ (bootstrap 2eab723…:52)
    at webpackJsonpCallback (bootstrap 2eab723…:23)
    at scripts.bundle.js:1
(anonymous) @ VM5316:11
webpackJsonp.297.module.exports @ addScript.js:9
186 @ angular2-recaptcha.js?d64c:1
__webpack_require__ @ bootstrap 2eab723…:52
902 @ addScript.js:10
__webpack_require__ @ bootstrap 2eab723…:52
webpackJsonpCallback @ bootstrap 2eab723…:23
(anonymous) @ scripts.bundle.js:1
metadata_resolver.js:972 Uncaught SyntaxError {__zone_symbol__error: Error: Unexpected value 'undefined' imported by the module 'DeclarationsModule'
    at SyntaxError.Z…, _nativeError: ZoneAwareError}`

**Comment by DethAriel** [comment]
Thank you guys for reporting this. 
@afu1991 are you using SystemJS, too? Cause I see a `__webpack_require__` there, which suggests otherwise. If you have an issue with webpack, please submit a different ticket

**Comment by DethAriel** [comment]
plus, @afu1991 , it looks like you're using a different module than this one, try visiting [its respective bugs page](https://github.com/xmaestro/angular2-recaptcha/issues)

**Comment by DethAriel** [comment]
@LucasFrecia I think your issue is that you configured SystemJS to use the "no-forms" version of recaptcha, but you're loading the `RecaptchaModule`, which is a forms one. Try loading `RecaptchaNoFormsModule` instead - see [this plunker](https://plnkr.co/edit/awOq8PIJvGBli8pIgL3b?p=preview) for reference.

Let me know if this resolves your issue

**Comment by DethAriel** [comment]
@LucasFrecia the problem might also be that you haven't specified the default extension to use, like this:
```js
System.config({ 
  // ...
  packages: { 
    'ng2-recaptcha': { 
      defaultJSExtensions: 'js',
    }, 
  },
}); 
```

**Comment by LucasFrecia** [comment]
thanks @DethAriel  :)
